api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register('questions', views.QuestionViewSet)
router.register('choices', views.ChoiceViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('questions/<int:question_id>/vote', views.choice_vote)
]

mysite/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.urls import path
from shop import views

urlpatterns = [
    path('api/', include('api.urls')),
    path('polls/', include('polls.urls')),
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
    path('accounts/register/', views.register, name='register')

]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

shop/urls.py
from django.urls import path

from . import views
from . import views

app_name = 'shop'
urlpatterns = [
    path('products', views.products_view, name='products'),
    path('product/<int:product_id>', views.product_detail, name='product_detail'),
    path('categories', views.categories_view, name='categories'),
    path('category/<int:category_id>', views.category_detail, name='category_detail')
]

polls/models.py
from django.db import models


# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.question.question_text} - {self.choice_text}'

shop/models.py
from django.db import models


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=200)


class Product(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.FloatField()
    category = models.ForeignKey(Category, related_name='products',
                                 on_delete=models.CASCADE)

polls/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'polls/index.html')

shop/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Category
from django.contrib.auth.forms import UserCreationForm


# Create your views here.

def products_view(request):
    context = {'products': Product.objects.all()}
    return render(request, 'shop/products.html', context)


def product_detail(request, product_id: int):
    context = {'product': get_object_or_404(Product, id=product_id)}
    return render(request, 'shop/product_detail.html', context)


def categories_view(request):
    context = {'categories': Category.objects.all()}
    return render(request, 'shop/categories.html', context)


def category_detail(request, category_id: int):
    context = {'category': get_object_or_404(Category, id=category_id)}
    return render(request, 'shop/category_detail.html', context)


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account is create {username}')
            return redirect('shop:products')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Polls</title>
</head>
<body>
    {% if user.is_authenticated %}
        <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn btn-danger"/>
        </form>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
    {% endif %}

    Hello world!
</body>
</html>

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Shop "Napitki"</title>
</head>
<body>
<div>
    <a href="{% url 'shop:products' %}">Products</a>
    <a href="{% url 'shop:categories' %}">Categories</a>

    {% if user.is_authenticated %}
        <form action="{% url 'logout' %}?next={{ request.path }}" method="post">
            {% csrf_token %}
            <input type="submit" value="Logout" class="btn btn-danger"/>
        </form>
    {% else %}
        <a href="{% url 'login' %}?next={{ request.path }}" class="btn btn-info">Login</a>
        <a href="{% url 'register'%}?next={{ request.path }}" class="btn-info">Register</a>
    {% endif %}
</div>
{% block body %}{% endblock %}
</body>
</html>

shop/templates/shop/categories.html
{% extends 'shop/base.html' %}

{% block body %}
<h1>Categories:</h1>
<ul>
    {% for category in categories %}
    <li>
        <a href="{% url 'shop:category_detail' category.id %}">{{ category.name }}</a>
    </li>

    {% endfor %}
</ul>
{% endblock %}

shop/templates/shop/category_detail.html
{% extends 'shop/base.html' %}

{% block body %}
<h1>{{ category.name }}</h1>
<ul>
    {% for product in category.products.all  %}
    <li><a href="{% url 'shop:product_detail' product.id%}">{{ product.name }}</a></li>


    {% endfor %}

{% endblock %}

shop/templates/shop/product_detail.html
{% extends 'shop/base.html' %}

{% block body %}
    <h1>{{ product.name }}</h1>

    <p>
        <a href="{% url 'shop:category_detail' product.category.id %}">{{ product.category.name }}</a>
    </p>
    <p>Price: {{ product.price }}$</p>
    <p>Decription: {{ product.description }}</p>

{% endblock %}

shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block body %}
<h1>Products:</h1>
<ul>
    {% for product in products %}
    <li>
        <a href="{% url 'shop:product_detail' product.id %}">{{ product.name }}</a>
    </li>

    {% endfor %}
</ul>
{% endblock %}